drop table if exists recipe CASCADE;
create table recipe (
id integer generated by default as identity, 
recipe_name VARCHAR(255) not null, 
category VARCHAR(255) not null, 
servings integer not null, 
cooking_time VARCHAR(65) not null, 
ingredients VARCHAR(255) not null,
primary key (id) 
);