drop table if exists recipe CASCADE;
create table recipe (
id integer generated by default as identity, 
recipe_name varchar(255) not null, 
category varchar(255) not null, 
servings integer not null, 
cooking_time varchar(65) not null, 
ingredients varchar(255) not null,
primary key (id) 
);